parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     3106
    database_name:     gighub
    database_user:     root

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    debug_toolbar:          true
    debug_redirects:        false
