gighub_application:
    resource: "@GighubApplicationBundle/Resources/config/routing.yml"
    prefix:   /

hello:
  pattern: /
  defaults:
    _controller: "Gighub\TrainingBundle\Controller\DefaultController::helloAction"


