gighub_application:
    resource: "@GighubApplicationBundle/Resources/config/routing.yml"
    prefix:   /

hello:
  pattern: /
  defaults:
    _controller: "Gighub\ApplicationBundle\Controller\UserController::homeAction"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook
