hwi_oauth:
    firewall_name: secured_area
    resource_owners:
        facebook:
            type:           facebook
            client_id:      %facebook_client_id%
            client_secret:  %facebook_client_secret%

security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        users:
            entity: { class: "Gighub\ApplicationBundle\Entity\User", property: username }

    encoders:
        Gighub\ApplicationBundle\Entity\User: bcrypt
