gighub_application_homepage:
    path:     /hello/{firstName}/{lastName}
    defaults: { _controller: GighubApplicationBundle:Default:index}

random:
        path:     /random/{limit}
        defaults: { _controller: GighubApplicationBundle:Random:index }

createShowDate:
        path:     /showdate/create/
        defaults: { _controller: GighubApplicationBundle:ShowDate:create }

showShowDate:
        path:     /showdate/show/{id}
        defaults: { _controller: GighubApplicationBundle:ShowDate:show }

updateShowDate:
        path:     /showdate/update/{id}/{updatedStatus}
        defaults: { _controller: GighubApplicationBundle:ShowDate:update }