gighub_application_homepage:
    path:     /hello/{firstName}/{lastName}
    defaults: { _controller: GighubApplicationBundle:Default:index}


createShowDate:
        path:     /showdate/create/
        defaults: { _controller: GighubApplicationBundle:ShowDate:create }

showShowDate:
        path:     /showdate/show/{id}
        defaults: { _controller: GighubApplicationBundle:ShowDate:show }

updateShowDate:
        path:     /showdate/update/{id}/{updatedStatus}
        defaults: { _controller: GighubApplicationBundle:ShowDate:update }

createArtist:
        path:     /artist/create/
        defaults: { _controller: GighubApplicationBundle:Artist:create }

showArtist:
        path:     /artist/show/{id}
        defaults: { _controller: GighubApplicationBundle:Artist:show }

uploadProfilePictureForArtist:
        path:     /artist/upload_profile_picture/{artist_id}
        defaults: { _controller: GighubApplicationBundle:Artist:uploadProfilePicture }

createUser:
        path:     /user/create/
        defaults: { _controller: GighubApplicationBundle:User:create }

showUser:
        path:     /user/show/{id}
        defaults: { _controller: GighubApplicationBundle:User:show }