services:
    gighub_application.auto_create_entity_user_provider:
        class: "Gighub\ApplicationBundle\Security\AutoCreateEntityUserProvider"
        arguments:
            - "@doctrine"
            - "Gighub\ApplicationBundle\Entity\User"
            - {"facebook": "username"}
